import localFont from 'next/font/local';
import ".././globals.css";
import LeftSidebar from '@/components/LeftSidebar';
import RightSidebar from '@/components/RightSidebar';
import { ClerkProvider, ClerkLoaded, ClerkLoading} from '@clerk/nextjs';
import Loader from '@/components/Loader';

const geistSans = localFont({
  src: ".././fonts/Geist/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",  
  weight: "100 900",
});

const geistMono = localFont({
  src: ".././fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",  
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ClerkLoading>
       <Loader />
       </ClerkLoading>
       <ClerkLoaded>
      <>
        <div className='flex justify-between max-w-6xl mx-auto'>
          <div className='h-screen border-r top-0 hidden sm:inline sticky'><LeftSidebar /></div>
          <div className='w-2xl flex-1'> {children}</div>
         
          <div className='lg:flex-col border-l p-3 h-screen hidden lg:flex w-[24rem]'><RightSidebar /></div>
        </div>
      </>
       </ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
